module.exports = {
  palette: {
    primary: '#3D7DFF',
    secondary: '#FFC200',
    black: '#222D47',
    dark_grey: '#5B647D',
    grey: '#CBCFD7',
    light_grey: '#F5F6FA',
    success: '#00D093',
    wrong: '#F12727',
    white: '#FFFFFF',
    grey_1: '#FBFCFD',
    grey_2: '#F4F7FC',
    grey_5_border: '#7C8589',
  },
  variables: {
    borderRadius: '3px',
    buttonSmallHeight: '24px',
    buttonMediumHeight: '30px',
    buttonLargeHeight: '40px',
    buttonSmallFontSize: '12px',
    buttonMediumFontSize: '13px',
    buttonLargeFontSize: '13px',
    inputMediumFontSize: '12px',
    inputLargeFontSize: '13px',
    inputMediumHeight: '30px',
    inputLargeHeight: '40px',
    textareaMediumHeight: '150px',
    textareaLargeHeight: '200px',
  },
};
