version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.5

aliases:
  - &docker-node-lts
    - image: cimg/node:16.15.0-browsers
      environment:
        CHROME_BIN: '/usr/bin/google-chrome'

  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: yarn-deps-{{ checksum "yarn.lock" }}

  - &restore-yarn-cache
    name: Restore yarnpkg cache
    key: yarn-cache

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    name: Save yarnpkg cache
    paths:
      - ~/.cache/yarn
    key: yarn-cache

jobs:
  checkout-code:
    docker: *docker-node-lts
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - restore_cache: *restore-node-modules-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - run:
          name: Check if yarn.lock changed during install
          command: git diff --exit-code
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: "."
          paths: [
            packages/*/node_modules
          ]

  lint:
    docker: *docker-node-lts
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: yarn lint

  test:
    docker: *docker-node-lts
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Verify Chrome browser installed
          command: |
            google-chrome --version
            chromedriver --version
      - run: yarn test

  build:
    docker: *docker-node-lts
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: yarn build
      - persist_to_workspace:
          root: "."
          paths: [
            packages/components/esm,
            packages/components/commonjs,
            packages/components/index.d.ts,
          ]

  deploy:
    docker: *docker-node-lts
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: |
          cd packages/docs-app
          yarn build
          yarn deploy:gh-pages

workflows:
  version: 2
  compile_lint_test_dist_deploy:
    jobs:
      - checkout-code
      - lint:
          requires: [
            checkout-code
          ]
      - test:
          requires: [
            checkout-code
          ]
      - build:
          requires: [
            lint,
            test
          ]
      - deploy:
          requires: [
            build
          ]
          filters:
            branches:
              only:
                - master

