version: 2.1

defaults: &defaults
  working_directory: ~/ci-build
  docker:
    - image: circleci/node:8.9.3

jobs:
  pre-build:
    <<: *defaults
    steps:
      - checkout:
          path: ~/ci-build/
      - attach_workspace:
          at: ~/ci-build/
      - restore_cache:
          key: dependency-cache-lib-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-lib-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run lint

  test-unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run test

  pre-build-deploy-docs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build/
      - restore_cache:
          key: dependency-cache-docs-{{ checksum "app/package.json" }}
      - run: cd app && npm install
      - save_cache:
          key: dependency-cache-docs-{{ checksum "app/package.json" }}
          paths:
            - app/node_modules
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - app/node_modules

  deploy-docs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run build && cd app && npm run deploy:gh-pages

  pre-build-theme-constructor:
    <<: *defaults
    steps:
      - checkout:
          path: ~/ci-build/
      - attach_workspace:
          at: ~/ci-build/
      - restore_cache:
          key: dependency-cache-lib-{{ checksum "theme-contructor/package.json" }}
      - run: cd theme-contructor && npm install
      - save_cache:
          key: dependency-cache-lib-{{ checksum "theme-contructor/package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - theme-contructor/node_modules

  lint-theme-contructor:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: cd theme-contructor && npm run lint

  test-unit-theme-contructor:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: cd theme-contructor && npm run test

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - pre-build
      - lint:
          requires:
            - pre-build
      - test-unit:
          requires:
            - pre-build
      - pre-build-deploy-docs:
          requires:
            - lint
            - test-unit
          filters:
            branches:
              only:
                - 0.3.x
      - deploy-docs:
          requires:
            - pre-build-deploy-docs
          filters:
            branches:
              only:
                - 0.3.x

      - pre-build-theme-constructor
      - lint-theme-contructor:
          requires:
            - pre-build-theme-constructor
      - test-unit-theme-contructor:
          requires:
            - pre-build-theme-constructor
