version: 2.1

defaults: &defaults
  working_directory: ~/ci-build
  docker:
    - image: circleci/node:8.9.3

jobs:
  pre-build:
    <<: *defaults
    steps:
      - checkout:
          path: ~/ci-build
      - attach_workspace:
          at: ~/ci-build
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run lint

  test-unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run test

  deploy-coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run coverage:deploy

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - pre-build
      - lint:
          requires:
            - pre-build
      - test-unit:
          requires:
            - lint
      - deploy-coverage:
          requires:
            - test-unit