version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:8.9.3

jobs:
  pre-build:
    working_directory: ~/ci-build
    <<: *defaults
    steps:
      - checkout:
          path: ~/ci-build/
      - attach_workspace:
          at: ~/ci-build/
      - restore_cache:
          key: dependency-cache-lib-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-lib-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - node_modules

  lint:
    working_directory: ~/ci-build
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run lint

  test-unit:
    working_directory: ~/ci-build
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: npm run test

  pre-build-deploy-docs:
    working_directory: ~/ci-build
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build/
      - restore_cache:
          key: dependency-cache-docs-{{ checksum "app/package.json" }}
      - run: cd app && npm install
      - save_cache:
          key: dependency-cache-docs-{{ checksum "app/package.json" }}
          paths:
            - app/node_modules
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - app/node_modules

  deploy-docs:
    working_directory: ~/ci-build
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - run: cd app && npm run deploy:gh-pages

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - pre-build
      - lint:
          requires:
            - pre-build
      - test-unit:
          requires:
            - lint
      - pre-build-deploy-docs:
          requires:
            - test-unit
          filters:
            branches:
              only:
                - ci-config-fix
      - deploy-docs:
          requires:
            - pre-build-deploy-docs
          filters:
            branches:
              only:
                - ci-config-fix