version: 2.1

defaults: &defaults
  working_directory: ~/ci-build
  docker:
    - image: circleci/node:10.17.0

jobs:
  theme-constructor:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: constructor-dependencies-{{ checksum "packages/theme-constructor/package.json" }}
      - run: cd packages/theme-constructor && npm install
      - save_cache:
          key: constructor-dependencies-{{ checksum "packages/theme-constructor/package.json" }}
          paths:
            - packages/theme-constructor/node_modules
      - run:
          name: Lint
          command: cd packages/theme-constructor && npm run lint
      - run:
          name: Test
          command: cd packages/theme-constructor && npm run test

  components:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: components-dependencies-{{ checksum "packages/components/package.json" }}
      - run: cd packages/components && npm install
      - save_cache:
          key: components-dependencies-{{ checksum "packages/components/package.json" }}
          paths:
            - packages/components/node_modules
      - run:
          name: Lint
          command: cd packages/components && npm run lint
      - run:
          name: Test
          command: cd packages/components && npm run test
      - run:
          name: Build
          command: cd packages/components && npm run build
      - persist_to_workspace:
          root: ~/ci-build
          paths:
            - packages/components/node_modules
            - packages/components/commonjs
            - packages/components/esm
            - packages/components/index.d.ts

  docs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-build
      - restore_cache:
          key: docs-dependencies-{{ checksum "packages/docs/package.json" }}
      - run: cd packages/docs && npm install
      - save_cache:
          key: docs-dependencies-{{ checksum "packages/docs/package.json" }}
          paths:
            - packages/docs/node_modules
      - run:
          name: Deploy to gh-pages
          command: cd packages/docs && npm run deploy:gh-pages

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - theme-constructor
      - components
      - docs:
          requires:
            - theme-constructor
            - components
          filters:
            branches:
              only:
                - master
