version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.17.0

jobs:
  pre-build:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test

  pre-build-deploy-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-docs-{{ checksum "app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-docs-
  
      - run: cd app && npm install
      - save_cache:
          paths:
            - app/node_modules
          key: v1-dependencies-docs-{{ checksum "app/package.json" }}

      - run: npm run build && cd app && npm run deploy:gh-pages

  # pre-build-theme-constructor:
  #   <<: *defaults
  #   steps:
  #     - checkout:
  #         path: ~/ci-build/
  #     - attach_workspace:
  #         at: ~/ci-build/
  #     - restore_cache:
  #         key: dependency-cache-lib-{{ checksum "theme-contructor/package.json" }}
  #     - run: cd theme-contructor && npm install
  #     - save_cache:
  #         key: dependency-cache-lib-{{ checksum "theme-contructor/package.json" }}
  #         paths:
  #           - node_modules
  #     - persist_to_workspace:
  #         root: ~/ci-build
  #         paths:
  #           - theme-contructor/node_modules

  # lint-theme-contructor:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: ~/ci-build
  #     - run: cd theme-contructor && npm run lint

  # test-unit-theme-contructor:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: ~/ci-build
  #     - run: cd theme-contructor && npm run test

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - pre-build
      - lint:
          requires:
            - pre-build
      - test-unit:
          requires:
            - pre-build
      - pre-build-deploy-docs:
          requires:
            - lint
            - test-unit
          filters:
            branches:
              only:
                - 0.3.x

      # - pre-build-theme-constructor
      # - lint-theme-contructor:
      #     requires:
      #       - pre-build-theme-constructor
      # - test-unit-theme-contructor:
      #     requires:
      #       - pre-build-theme-constructor
