version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.17.0

jobs:
  theme-constructor:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: constructor-dependencies-{{ checksum "packages/theme-constructor/package.json" }}
      - run:
          name: Install dependencies
          command: cd packages/theme-constructor && npm install
      - save_cache:
          key: constructor-dependencies-{{ checksum "packages/theme-constructor/package.json" }}
          paths:
            - ./packages/theme-constructor/node_modules
      - run:
          name: Lint
          command: cd packages/theme-constructor && npm lint
      - run:
          name: Test
          command: cd packages/theme-constructor && npm test

workflows:
  version: 2
  theme-constructor-flow:
    jobs:
      - theme-constructor
